Preparing AbacusSummit_base_c103_ph000 0.800
/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf.extensions plugin from package asdf-astropy==0.6.1 failed to load:

KeyError: 'Resource unavailable for URI: asdf://asdf-format.org/transform/manifests/transform-1.6.0'
  warnings.warn(
compiling compaso halo catalogs into subsampled catalogs
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/code/abacusutils/main/lib/python3.10/site-packages/abacusnbody/hod/prepare_sim.py", line 329, in prepare_slab
    cat = CompaSOHaloCatalog(slabname, subsamples=dict(A=True, rv=True), fields = [N_key,
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/code/abacusutils/main/lib/python3.10/site-packages/abacusnbody/data/compaso_halo_catalog.py", line 192, in __init__
    self.cleaned_halo_fns) = self._setup_file_paths(path, cleaned=cleaned, cleandir=cleandir, halo_lc=halo_lc)
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/code/abacusutils/main/lib/python3.10/site-packages/abacusnbody/data/compaso_halo_catalog.py", line 362, in _setup_file_paths
    raise FileNotFoundError(f'Cleaning info not found. File path was: "{fn}". To load the uncleaned catalog, use `cleaned=False`.')
FileNotFoundError: Cleaning info not found. File path was: "/global/cfs/cdirs/desi/cosmosim/Abacus/cleaning/AbacusSummit_base_c103_ph000/z0.800/cleaned_halo_info/cleaned_halo_info_005.asdf". To load the uncleaned catalog, use `cleaned=False`.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/code/abacusutils/main/lib/python3.10/site-packages/abacusnbody/hod/prepare_sim.py", line 817, in <module>
    main(**args)
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/code/abacusutils/main/lib/python3.10/site-packages/abacusnbody/hod/prepare_sim.py", line 785, in main
    p.starmap(prepare_slab, zip(range(numslabs), repeat(savedir),
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20240118-1.0.0/conda/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: Cleaning info not found. File path was: "/global/cfs/cdirs/desi/cosmosim/Abacus/cleaning/AbacusSummit_base_c103_ph000/z0.800/cleaned_halo_info/cleaned_halo_info_005.asdf". To load the uncleaned catalog, use `cleaned=False`.
processing slab  5
loading halo catalog 
processing slab  10
loading halo catalog 
processing slab  20
loading halo catalog 
processing slab  30
loading halo catalog 
processing slab  0
loading halo catalog 
processing slab  15
loading halo catalog 
processing slab  25
loading halo catalog 
